version: '3.8'

services:
  postgres:
    image: 'postgres:v${POSTGRES_VERSION}'
    container_name: postgres
    build: ./database
    restart: always

    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  db_data:
