const OUTPUT_TO_CONSOLE = true;
const LOG_ERRORS_IN_ERROR_FILE = true;
const WRITING_LOG_TO_FILE = true;

const LOG_FILE_NAME = 'log.txt';
const ERROR_FILE_NAME = 'error.txt';

export {
  OUTPUT_TO_CONSOLE,
  LOG_ERRORS_IN_ERROR_FILE,
  WRITING_LOG_TO_FILE,
  LOG_FILE_NAME,
  ERROR_FILE_NAME,
};
